

server:
  port: 8081

spring:
  security:
    oauth2:
      client:
        registration:
          mywebclient:
           client-id: myclient
           client-secret: ad8da2cc-9ee4-4767-83dc-7192f1ed041d
           authorization-grant-type: client_credentials
           
        provider:
          mywebclient:
            issuer-uri: http://localhost:28080/auth/realms/myrealm
            token-uri: http://localhost:28080/auth/realms/myrealm/protocol/openid-connect/token
            
          
            
